#!/bin/bash
set -e

# proxy
os_type="$(uname -s)"
proxy=""

if [[ "$os_type" == MINGW* || "$os_type" == MSYS* || "$os_type" == CYGWIN* ]]; then
    proxy=$(reg query "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:[0-9]+")
elif [[ "$os_type" == "Darwin" ]]; then
    port=$(networksetup -getwebproxy "Wi-Fi" 2>/dev/null | grep Port | awk '{print $2}')
    server=$(networksetup -getwebproxy "Wi-Fi" 2>/dev/null | grep Server | awk '{print $2}')
    
    if [[ "$port" == "0" || -z "$server" ]]; then
        port=$(networksetup -getwebproxy "Ethernet" 2>/dev/null | grep Port | awk '{print $2}')
        server=$(networksetup -getwebproxy "Ethernet" 2>/dev/null | grep Server | awk '{print $2}')
    fi

    if [[ "$port" != "0" && -n "$server" ]]; then
        proxy="$server:$port"
    fi
fi

if [[ -n "$proxy" ]]; then
    export http_proxy="http://$proxy"
    export https_proxy="http://$proxy"
fi

# schema
git clone https://github.com/rimeinn/rime-moran.git --branch trad --depth 1
rm -rf rime-moran/.git
cp -rf rime-moran/* .
rm -rf rime-moran

# gram
curl -L -O  "https://media.githubusercontent.com/media/rimeinn/octagram-data/refs/heads/master/models/fcitx/fcitx-zh-hant.gram?download=true"
